"""Research-grade tools for SWOT L2 HR PIXC workflows."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .bank_inference import (
    CandidateIntervalConfiguration,
    CandidateIntervalInferenceResult,
    CandidateIntervalSensitivityResult,
    CandidateSourceSummary,
    CandidateWetInterval,
    GapBridgeRecord,
    StationBinEvidence,
    StationBinState,
    infer_candidate_wet_intervals,
    run_candidate_interval_sensitivity,
)
from .benchmark import (
    ANNOTATION_INPUT_SCHEMA_VERSION,
    ANNOTATION_REQUIRED_MESSAGE,
    APPROVED_TRANSECT_STATUS,
    BENCHMARK_CONFIG_SCHEMA_VERSION,
    PILOT_GRID_NOTICE,
    PROPOSED_TRANSECT_STATUS,
    AnnotationPacket,
    BenchmarkConfig,
    BenchmarkObservation,
    BenchmarkPreparationResult,
    BenchmarkRunResult,
    BenchmarkTransect,
    ManualAnnotation,
    ReferenceImageryMetadata,
    SensitivityGrid,
    TransectManifest,
    TransectProposalSettings,
    aggregate_benchmark_results,
    expand_sensitivity_grid,
    generate_annotation_packets,
    load_benchmark_config,
    load_manual_annotations,
    load_transect_manifest,
    propose_candidate_transects,
    run_benchmark,
    save_manual_annotation,
    station_frame_hash,
    write_transect_manifest,
)
from .constants import (
    DEFAULT_PIXC_COLLECTION_CONCEPT_ID,
    DEFAULT_PIXC_SHORT_NAME,
    DEFAULT_PIXC_VERSION,
)
from .discovery import GranuleRecord
from .exceptions import (
    AnnotationRequiredError,
    AoiError,
    BankInferenceError,
    BenchmarkError,
    CacheIntegrityError,
    DateRangeError,
    DiscoveryError,
    DownloadError,
    LocalFilesUnavailableError,
    ObservationMismatchError,
    PixcLabError,
    PixcOpenError,
    PixcSchemaError,
    QualityMetadataError,
    TransectError,
    ValidationError,
    WidthError,
)
from .mosaic import PixcObservation, open_pixc
from .pixc import LocalPixcCollection, PixcCollection, SearchProvenance
from .qc import (
    QC_PROFILES,
    DecodedQualityFlags,
    FlagDefinition,
    HeightReferenceResult,
    QCProfile,
    QCResult,
    QCRule,
    QCRuleOutcome,
    apply_qc,
    decode_quality_flags,
)
from .reader import (
    PHASE3_POINT_VARIABLES,
    PixcSourceMetadata,
    PixcVariableMetadata,
)
from .transect import TransectSample, sample_transect
from .validation import (
    BoundaryDistanceMetrics,
    IntervalSetMetrics,
    IntervalValidationResult,
    ManualBenchmarkMetadata,
    ManualBenchmarkRecord,
    SensitivityValidationResult,
    create_manual_benchmark_record,
    evaluate_candidate_against_explicit,
    evaluate_sensitivity_against_explicit,
)
from .visualization import (
    CLASSIFICATION_COLORS,
    CLASSIFICATION_LABELS,
    SUPPORTED_COLOR_VARIABLES,
    plot_candidate_wet_interval_inference,
    plot_classification_comparison,
    plot_interval_validation,
    plot_pixc_map,
    plot_transect_classification,
    plot_transect_corridor,
    plot_transect_height,
    plot_wet_interval_summary,
)
from .width import (
    DryGap,
    ExplicitIntervalWidthResult,
    WetInterval,
    WidthSourceSummary,
    measure_explicit_wet_intervals,
)

try:
    __version__ = version("swot-pixc-lab")
except PackageNotFoundError:  # source checkout without an editable install
    __version__ = "0+unknown"

__all__ = [
    "ANNOTATION_INPUT_SCHEMA_VERSION",
    "ANNOTATION_REQUIRED_MESSAGE",
    "APPROVED_TRANSECT_STATUS",
    "AoiError",
    "AnnotationPacket",
    "AnnotationRequiredError",
    "BENCHMARK_CONFIG_SCHEMA_VERSION",
    "BankInferenceError",
    "BenchmarkConfig",
    "BenchmarkError",
    "BenchmarkObservation",
    "BenchmarkPreparationResult",
    "BenchmarkRunResult",
    "BenchmarkTransect",
    "BoundaryDistanceMetrics",
    "CacheIntegrityError",
    "CandidateIntervalConfiguration",
    "CandidateIntervalInferenceResult",
    "CandidateIntervalSensitivityResult",
    "CandidateSourceSummary",
    "CandidateWetInterval",
    "CLASSIFICATION_COLORS",
    "CLASSIFICATION_LABELS",
    "DEFAULT_PIXC_COLLECTION_CONCEPT_ID",
    "DEFAULT_PIXC_SHORT_NAME",
    "DEFAULT_PIXC_VERSION",
    "DateRangeError",
    "DiscoveryError",
    "DownloadError",
    "DryGap",
    "ExplicitIntervalWidthResult",
    "GranuleRecord",
    "GapBridgeRecord",
    "IntervalSetMetrics",
    "IntervalValidationResult",
    "LocalFilesUnavailableError",
    "LocalPixcCollection",
    "ManualBenchmarkMetadata",
    "ManualBenchmarkRecord",
    "ManualAnnotation",
    "ObservationMismatchError",
    "PHASE3_POINT_VARIABLES",
    "PixcCollection",
    "PixcLabError",
    "PixcObservation",
    "PixcOpenError",
    "PixcSchemaError",
    "PixcSourceMetadata",
    "PixcVariableMetadata",
    "PILOT_GRID_NOTICE",
    "PROPOSED_TRANSECT_STATUS",
    "QC_PROFILES",
    "DecodedQualityFlags",
    "FlagDefinition",
    "HeightReferenceResult",
    "QCProfile",
    "QCResult",
    "QCRule",
    "QCRuleOutcome",
    "QualityMetadataError",
    "SearchProvenance",
    "ReferenceImageryMetadata",
    "SensitivityGrid",
    "SensitivityValidationResult",
    "StationBinEvidence",
    "StationBinState",
    "SUPPORTED_COLOR_VARIABLES",
    "TransectError",
    "TransectManifest",
    "TransectProposalSettings",
    "TransectSample",
    "ValidationError",
    "WetInterval",
    "WidthError",
    "WidthSourceSummary",
    "__version__",
    "apply_qc",
    "aggregate_benchmark_results",
    "create_manual_benchmark_record",
    "decode_quality_flags",
    "evaluate_candidate_against_explicit",
    "evaluate_sensitivity_against_explicit",
    "expand_sensitivity_grid",
    "generate_annotation_packets",
    "infer_candidate_wet_intervals",
    "load_benchmark_config",
    "load_manual_annotations",
    "load_transect_manifest",
    "open_pixc",
    "measure_explicit_wet_intervals",
    "plot_classification_comparison",
    "plot_candidate_wet_interval_inference",
    "plot_pixc_map",
    "plot_interval_validation",
    "plot_transect_classification",
    "plot_transect_corridor",
    "plot_transect_height",
    "plot_wet_interval_summary",
    "propose_candidate_transects",
    "run_benchmark",
    "save_manual_annotation",
    "sample_transect",
    "station_frame_hash",
    "run_candidate_interval_sensitivity",
    "write_transect_manifest",
]
